name: lung_study_lstm_anomaly_detection
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - matplotlib
  - pip:
    - mlflow
    - -r file:../../requirements.txt
variables:
  MLFLOW_URL: http://127.0.0.1:5000
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:9000
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: