name: linear_regression_remote_example
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - mlflow
    - -r file:../../requirements.txt
variables:
  MLFLOW_URL: http://127.0.0.1:5000
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:9000
  AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY