name: Run Python Tests
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install linux dependencies
        run: sudo apt-get install postgresql
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model-builder/requirements.txt
      - name: Run tests with pytest
        run: pytest