# Create release files
name: Release

on:
    release:
        types: [ published ]
jobs:
    # Build and push tagged release docker image
    model-invocation-endpoint-docker:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        env:
            DOCKER_IMAGE: model-builder/model-invocation-endpoint
            DOCKERHUB_IMAGE: radarbase/model-invocation-endpoint

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            -   uses: actions/checkout@v2

            # Setup docker build environment
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Add Docker labels and tags
            -   name: Docker meta
                id: docker_meta
                uses: docker/metadata-action@v3
                with:
                    images: ${{ env.DOCKERHUB_IMAGE }}
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
            -   name: Build docker
                uses: docker/build-push-action@v2
                with:
                    # Allow running the image on the architectures supported by openjdk:11-jre-slim
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags }}
            -   name: Inspect docker image
                run: |
                    docker pull ${{ env.DOCKERHUB_IMAGE }}:${{ steps.docker_meta.outputs.version }}
                    docker image inspect ${{ env.DOCKERHUB_IMAGE }}:${{ steps.docker_meta.outputs.version }}
    # Build and push tagged release docker image
    model-builder-docker:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        env:
            DOCKER_IMAGE: model-builder/model-builder/ml_models/
            DOCKERHUB_IMAGE: radarbase/model-builder

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            -   uses: actions/checkout@v2

            # Setup docker build environment
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Add Docker labels and tags
            -   name: Docker meta
                id: docker_meta
                uses: docker/metadata-action@v3
                with:
                    images: ${{ env.DOCKERHUB_IMAGE }}
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
            -   name: Build docker
                uses: docker/build-push-action@v2
                with:
                    # Allow running the image on the architectures supported by openjdk:11-jre-slim
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags }}
            -   name: Inspect docker image
                run: |
                    docker pull ${{ env.DOCKERHUB_IMAGE }}:${{ steps.docker_meta.outputs.version }}
                    docker image inspect ${{ env.DOCKERHUB_IMAGE }}:${{ steps.docker_meta.outputs.version }}
